version: 2.1

build-job: &build-job
    steps:
        - checkout

        - restore_cache:
            keys:
                # Restart caching for every new wrapper and add job name (= JDK version) as JDK influences Gradle's caching
                - gradle-repo-v2-{{ .Environment.CIRCLE_JOB }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

        - run: ./gradlew --build-cache build

        # - run:
        #     command: |
        #         ./gradlew jacocoTestReport
        #         bash <(curl -s https://codecov.io/bash)

        - save_cache:
            paths:
                - ~/.gradle
            key: gradle-repo-v2-{{ .Environment.CIRCLE_JOB }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

        - store_test_results:
            path: ./build/test-results

jobs:
    jdk11:
        docker:
            - image: cimg/openjdk:11.0
        <<: *build-job
    jdk17:
        docker:
            - image: cimg/openjdk:17.0
        <<: *build-job
    jdk21:
        docker:
            - image: cimg/openjdk:21.0
        <<: *build-job
    jdk22:
        docker:
            - image: cimg/openjdk:22.0
        <<: *build-job

workflows:
    version: 2
    build:
        jobs:
            - jdk11
            - jdk17
            # - jdk21 -> Gradle's groovy not compatible
            # - jdk22 -> no jdk available yet
